- FIELD1: Country
  FIELD2: CustomerId
- FIELD1: US
  FIELD2: '1234'
- FIELD1: BR
  FIELD2: '2345'
- FIELD1: CA
  FIELD2: '3456'
- FIELD1: MX
  FIELD2: '4567'
- FIELD1: DE
  FIELD2: '5678'
- FIELD1: GB
  FIELD2: '6789'
- FIELD1: JP
  FIELD2: '7890'
